[build]
target = "xtensa-esp32-espidf"

[unstable]
build-std = ["std", "core", "alloc", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"

[alias]
runesp = "run --release -- --port /dev/ttyUSB0"
buildesp = "build"
